version: '3.9'
services:
    postgres:
        image: postgres:14beta2-buster
        container_name: postgres
        restart: unless-stopped
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_DB=nft
        volumes:
            - db-data:/var/lib/postgresql/data
        ports:
            - 5432:5432/tcp
    pgadmin:
        image: dpage/pgadmin4:5.6
        container_name: pgadmin
        restart: unless-stopped
        environment:
            - PGADMIN_DEFAULT_EMAIL=postgres@localhost.dev
            - PGADMIN_DEFAULT_PASSWORD=postgres
            - PGADMIN_LISTEN_ADDRESS=0.0.0.0
            - PGADMIN_LISTEN_PORT=5480
        ports:
            - 5480:5480/tcp
    scraper:
        build: .
        image: scraper:1.0
        container_name: scraper
        restart: unless-stopped
        environment:
            - DSN=postgres://postgres:postgres@postgres/nft?sslmode=disable
            - NFTPORT_API_KEY=<API_KEY>
        ports:
            - 4444:4444/tcp

volumes:
    db-data:

